# Generated by Django 5.2.11 on 2026-02-20 06:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '__first__'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('published_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='author.author')),
                ('genres', models.ManyToManyField(related_name='books', to='genre.genre')),
            ],
            options={
                'ordering': ['title', '-created_date'],
                'indexes': [models.Index(fields=['title'], name='book_book_title_b5b75a_idx')],
            },
        ),
    ]
