# Generated by Django 5.2.11 on 2026-02-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
    ]
