# Generated by Django 5.2.11 on 2026-02-20 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_my_custom_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='Enter 10 or 13 digit ISBN (with or without hyphens)', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10 or 13 digit ISBN.', regex='^(?=(?:\\D*\\d){10}(?:(?:\\D*\\d){3})?$)[\\d-]+$')]),
        ),
    ]
