# Generated by Django 5.2.11 on 2026-02-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='Enter 10 digit ISBN', max_length=10, unique=True),
        ),
    ]
