# Generated by Django 5.2 on 2026-02-26 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
        ("book", "0006_alter_book_isbn"),
        ("genre", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text="Enter 13 digit ISBN",
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{13}$", message="ISBN must be exactly 13 digits"
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["published_date"], name="book_book_publish_9e2df9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["isbn"], name="book_book_isbn_6f139e_idx"),
        ),
    ]
